version: '3'

services:
  redzilla:
    image: opny/redzilla
    environment:
      DOCKER_API_VERSION: 1.39
      # compose created network name
      REDZILLA_NETWORK: redzilla_redzilla
      REDZILLA_DOMAIN: redzilla.localhost
      REDZILLA_IMAGENAME: docker.io/nodered/node-red-docker:latest
    networks:
      - redzilla
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

networks:
  redzilla:
    driver: bridge
